### ISSUE TITLE
Portuguese remainings

### ISSUE THREAD

**Issue by sahcamargo** [elisamussumeci/zika_virus_timeline#27]
"Timeline de Publicações" and "Série Temporal" are still displayed in portuguese

**Comment by fccoelho** [comment]
fixed. @flavioamieiro, did you update the deploy?

**Comment by flavioamieiro** [comment]
@fccoelho I'm building the new Docker right now. It should be up in a few.

**Comment by flavioamieiro** [comment]
I've had a few problems with the new deploy. I've fixed them, and also added 6322702 to translate the title of the time series plot (that was inside the javascript file). Everything is now online. Thank you @sahcamargo for the report and @fccoelho for the fix.
